load("@rules_python//python:defs.bzl", "py_binary")
load("@infra//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_binary(
  name = "main",
  srcs = ["main.py"],
)